### ISSUE TITLE
highlights on javascript files

### ISSUE THREAD

**Issue by Jchael12** [DanielEliasib/sweet-fusion#1]
![image](https://github.com/DanielEliasib/sweet-fusion/assets/120585376/6929e1dd-27fd-4b71-9b01-83aeb78bc62e)

is this syntax highlighting normal on javascript files ? thank you :)

**Comment by DanielEliasib** [comment]
hi, I don't write javascript but I made a small test file and it does look the same, do you think it should have more variation?

**Comment by Jchael12** [comment]
I think it will be very nice if you give it more just like the C from your sample screenshot, but overall very nice theme !

**Comment by DanielEliasib** [comment]
thanks, I'll try to work on it on the weekend

**Comment by DanielEliasib** [comment]
Hey @Jchael12, can you check #2 to see if highlighting has improved in a real project?

**Comment by Jchael12** [comment]
Hi @DanielEliasib I just visited your colorscheme now. I'll let you know the results after I test it :) thanks !

**Comment by Jchael12** [comment]
update: sorry if I didn't mention this last time, but the project I had in the prev screenshot is a react jsx project. and as I notice from your latest update, the syntax highlighting is still the same with the filetype of .jsx . The highlights on a vanilla javascript is okay its just needs a little touch of green, yellow, and blue and it's fantastic. But overall the theme is good just needs a touch of those color combination. Thank you and have a great day.

**Comment by DanielEliasib** [comment]
yeah, i noticed it was a jsx project, I didn't add any specific js/jsx highlight groups because I noticed that the repetitive colors where mainly coming from default hl groups that used pink/purpled.

this is how it looks on my side right now, I used some files from one of your projects because I don't really do js, so I don't have projects where to test, maybe users of specific lenguages can open PRs for the specific lenguage highlight groups, I'm guessing someone more familiar can add more variation.

![image](https://github.com/DanielEliasib/sweet-fusion/assets/46411530/7347c1ef-de54-4b16-8a27-757c53e1fffd)
(Edit: updated image, I was using an old version)

**Comment by Jchael12** [comment]
okay got it, thank you for your efforts and looking forward for updates in this theme :)

**Comment by DanielEliasib** [comment]
these changes, and some new ones, are already merged, I'll close this for now, let me now if you catch some other problems
